"""initial schema

Revision ID: a1d7950da92e
Revises: 
Create Date: 2026-03-09 17:42:22.644407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1d7950da92e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('nse_symbol', sa.String(length=20), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nse_symbol'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index('ix_stocks_is_active', 'stocks', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=200), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asm_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_asm_current', 'asm_entries', ['stock_id'], unique=False, postgresql_where=sa.text('is_current = true'))
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('before_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_log', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_table('board_meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('meeting_date', sa.Date(), nullable=True),
    sa.Column('announcement_date', sa.Date(), nullable=True),
    sa.Column('quarter', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_board_meetings_date', 'board_meetings', ['meeting_date'], unique=False)
    op.create_table('circuit_bands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('series', sa.String(length=10), nullable=True),
    sa.Column('band_pct', sa.Integer(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color_classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=10), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_color_current', 'color_classifications', ['stock_id'], unique=False, postgresql_where=sa.text('is_current = true'))
    op.create_table('daily_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('low', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('close', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_daily_prices_date_desc', 'daily_prices', ['stock_id', sa.literal_column('date DESC')], unique=False)
    op.create_index('ix_daily_prices_stock_date', 'daily_prices', ['stock_id', 'date'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_stock_created', 'events', ['stock_id', 'created_at'], unique=False)
    op.create_index('ix_events_type_created', 'events', ['event_type', 'created_at'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('author_type', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notes_stock_created', 'notes', ['stock_id', 'created_at'], unique=False)
    op.create_table('result_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.String(length=10), nullable=True),
    sa.Column('result_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_result_dates_date', 'result_dates', ['result_date'], unique=False)
    op.create_index('ix_result_dates_stock_quarter', 'result_dates', ['stock_id', 'quarter'], unique=True)
    op.create_table('screeners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('stock_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('prev_close', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pct_change', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('pe', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('market_cap_cr', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('today_high', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('today_low', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('today_open', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('today_volume', sa.BigInteger(), nullable=True),
    sa.Column('dma_10', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('dma_20', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('dma_50', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('dma_100', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('dma_200', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('dma_10_touch', sa.Boolean(), nullable=False),
    sa.Column('dma_20_touch', sa.Boolean(), nullable=False),
    sa.Column('dma_50_touch', sa.Boolean(), nullable=False),
    sa.Column('dma_100_touch', sa.Boolean(), nullable=False),
    sa.Column('dma_200_touch', sa.Boolean(), nullable=False),
    sa.Column('dma_10_signal', sa.String(length=10), nullable=True),
    sa.Column('dma_20_signal', sa.String(length=10), nullable=True),
    sa.Column('dma_50_signal', sa.String(length=10), nullable=True),
    sa.Column('dma_100_signal', sa.String(length=10), nullable=True),
    sa.Column('dma_200_signal', sa.String(length=10), nullable=True),
    sa.Column('wma_5', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('wma_10', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('wma_20', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('wma_30', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('wma_5_touch', sa.Boolean(), nullable=False),
    sa.Column('wma_10_touch', sa.Boolean(), nullable=False),
    sa.Column('wma_20_touch', sa.Boolean(), nullable=False),
    sa.Column('wma_5_signal', sa.String(length=10), nullable=True),
    sa.Column('wma_10_signal', sa.String(length=10), nullable=True),
    sa.Column('wma_20_signal', sa.String(length=10), nullable=True),
    sa.Column('high_52w', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_52w_high_intraday', sa.Boolean(), nullable=False),
    sa.Column('is_52w_closing_high', sa.Boolean(), nullable=False),
    sa.Column('was_52w_high_yesterday', sa.Boolean(), nullable=False),
    sa.Column('prev_52w_closing_high', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('high_52w_date', sa.Date(), nullable=False),
    sa.Column('max_vol_21d', sa.BigInteger(), nullable=True),
    sa.Column('avg_vol_140d', sa.BigInteger(), nullable=True),
    sa.Column('avg_vol_280d', sa.BigInteger(), nullable=True),
    sa.Column('is_volume_breakout', sa.Boolean(), nullable=False),
    sa.Column('biweek_high', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('biweek_vol', sa.BigInteger(), nullable=True),
    sa.Column('is_biweek_bo', sa.Boolean(), nullable=False),
    sa.Column('week_high', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('week_vol', sa.BigInteger(), nullable=True),
    sa.Column('is_week_bo', sa.Boolean(), nullable=False),
    sa.Column('gap_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('is_gap_up', sa.Boolean(), nullable=False),
    sa.Column('is_gap_down', sa.Boolean(), nullable=False),
    sa.Column('high_90d', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('low_90d', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_90d_high', sa.Boolean(), nullable=False),
    sa.Column('is_90d_low_touch', sa.Boolean(), nullable=False),
    sa.Column('days_to_result', sa.Integer(), nullable=True),
    sa.Column('result_within_7d', sa.Boolean(), nullable=False),
    sa.Column('result_within_10d', sa.Boolean(), nullable=False),
    sa.Column('result_within_15d', sa.Boolean(), nullable=False),
    sa.Column('result_declared_10d', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_indicators_52w_closing', 'stock_indicators', ['date'], unique=False, postgresql_where=sa.text('is_52w_closing_high = true'))
    op.create_index('ix_indicators_date', 'stock_indicators', ['date'], unique=False)
    op.create_index('ix_indicators_dma10_touch', 'stock_indicators', ['date'], unique=False, postgresql_where=sa.text('dma_10_touch = true'))
    op.create_index('ix_indicators_stock_date', 'stock_indicators', ['stock_id', 'date'], unique=True)
    op.create_index('ix_indicators_vol_breakout', 'stock_indicators', ['date'], unique=False, postgresql_where=sa.text('is_volume_breakout = true'))
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_watchlist_user_stock', 'watchlists', ['user_id', 'stock_id'], unique=True)
    op.create_table('webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('secret', sa.String(length=100), nullable=True),
    sa.Column('event_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('week_ending', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('low', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('close', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_weekly_prices_stock_week', 'weekly_prices', ['stock_id', 'week_ending'], unique=True)
    op.create_table('screener_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screener_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=50), nullable=False),
    sa.Column('operator', sa.String(length=20), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['screener_id'], ['screeners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screener_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screener_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('entered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['screener_id'], ['screeners.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_screener_history_screener_date', 'screener_history', ['screener_id', 'date'], unique=False)
    op.create_index('ix_screener_history_stock_screener', 'screener_history', ['stock_id', 'screener_id', 'date'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webhook_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook_deliveries')
    op.drop_index('ix_screener_history_stock_screener', table_name='screener_history')
    op.drop_index('ix_screener_history_screener_date', table_name='screener_history')
    op.drop_table('screener_history')
    op.drop_table('screener_conditions')
    op.drop_index('ix_weekly_prices_stock_week', table_name='weekly_prices')
    op.drop_table('weekly_prices')
    op.drop_table('webhooks')
    op.drop_index('ix_watchlist_user_stock', table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index('ix_indicators_vol_breakout', table_name='stock_indicators', postgresql_where=sa.text('is_volume_breakout = true'))
    op.drop_index('ix_indicators_stock_date', table_name='stock_indicators')
    op.drop_index('ix_indicators_dma10_touch', table_name='stock_indicators', postgresql_where=sa.text('dma_10_touch = true'))
    op.drop_index('ix_indicators_date', table_name='stock_indicators')
    op.drop_index('ix_indicators_52w_closing', table_name='stock_indicators', postgresql_where=sa.text('is_52w_closing_high = true'))
    op.drop_table('stock_indicators')
    op.drop_table('screeners')
    op.drop_index('ix_result_dates_stock_quarter', table_name='result_dates')
    op.drop_index('ix_result_dates_date', table_name='result_dates')
    op.drop_table('result_dates')
    op.drop_index('ix_notes_stock_created', table_name='notes')
    op.drop_table('notes')
    op.drop_index('ix_events_type_created', table_name='events')
    op.drop_index('ix_events_stock_created', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_daily_prices_stock_date', table_name='daily_prices')
    op.drop_index('ix_daily_prices_date_desc', table_name='daily_prices')
    op.drop_table('daily_prices')
    op.drop_index('ix_color_current', table_name='color_classifications', postgresql_where=sa.text('is_current = true'))
    op.drop_table('color_classifications')
    op.drop_table('circuit_bands')
    op.drop_index('ix_board_meetings_date', table_name='board_meetings')
    op.drop_table('board_meetings')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_asm_current', table_name='asm_entries', postgresql_where=sa.text('is_current = true'))
    op.drop_table('asm_entries')
    op.drop_table('api_keys')
    op.drop_table('users')
    op.drop_index('ix_stocks_is_active', table_name='stocks', postgresql_where=sa.text('is_active = true'))
    op.drop_table('stocks')
    # ### end Alembic commands ###
